version: '2.1'
services:
    clickhouse:
        image: yandex/clickhouse-server:21.8.8.29 
        ulimits:
          nofile:
            soft: 262144
            hard: 262144
        ports:
            - 8123:8123
        volumes:
            - ./config.xml:/etc/clickhouse-server/config.xml
            - ./data:/var/lib/clickhouse
