version: '3.1'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
